name: GitHub Actions Try # ワークフローの名前
# on.workflow_dispatch.inputs
on:
  workflow_dispatch:
    inputs: # inputs文脈
      branch_name: # パラメータ名
        description: 'BRANCH NAME(e.g. main)' # 説明
        required: true # true:入力必須, false:入力任意
        default: 'main' # 規定値は'main'
    
jobs:
  Try-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: practice of YAML
        id: practice
        run: |
          echo 'BRANCH NAME is ${{ inputs.branch_name }}'
          echo ${GITHUB_REF}          # refs/heads/[branch名]
          echo ${{ github.ref }}      # refs/heads/[branch名]
          echo ${{ github.ref_name }} # [branch名]
          BRANCH1=$(echo ${GITHUB_REF} | rev | cut -d'/' -f1 | rev) #revコマンドは文字を逆に変換
          echo ${BRANCH1}
          BRANCH2=${BRANCH1}_${{ github.event.inputs.branch_name }}_${{ github.ref_name }}
          echo ${BRANCH2}

          branch_input='main'
          if [ ${{ github.event.inputs.branch_name }} != "${branch_input}" ]; then
            std_input=0
          else
            std_input=1
          fi
          echo ${std_input}

          echo ${{ github.event.repository.name }}
# refs/heads/[branch名] -> [branch名]を抽出
# EOF