name: GitHub Actions Demo # ワークフローの名前
# on.workflow_dispatch.inputs
on:
  workflow_dispatch:
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
      - name: Run a one-line script
      - run: echo Hello World!!
# EOF