name: GitHub Actions Try # ワークフローの名前
# on.workflow_dispatch.inputs
on:
  workflow_dispatch:
    inputs: # inputs文脈
      branch_name: # パラメータ名
        description: 'BRANCH NAME(e.g. main)' # 説明
        required: true # true:入力必須, false:入力任意
        default: 'main' # 規定値は'main'
    
jobs:
  Try-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: practice of YAML
        id: practice
        run: |
          echo 'BRANCH NAME is ${{ inputs.branch_name }}'
          echo ${GITHUB_REF}
          BRANCH=$(echo ${GITHUB_REF} | rev | cut -d'/' -f1 | rev) #revコマンドは文字を逆に変換
          echo ${BRANCH}
          echo ${{ github.event.inputs.branch_name }}
#          echo "::set-output name=branchname::$BRANCH"
#          echo "branchname=${BRANCH}" >> ${GITHUB_OUTPUT}
#          echo ${{steps.vars.outputs.branchname}}
# refs/heads/[branch名] -> [branch名]を抽出
# EOF