name: GitHub Actions Try # ワークフローの名前
# on.workflow_dispatch.inputs
on:
  workflow_dispatch:
    inputs: # inputs文脈
      branch_name: # パラメータ名
        description: 'BRANCH NAME(e.g. main)' # 説明
        required: true # true:入力必須, false:入力任意
        default: 'main' # 規定値は'main'
    
jobs:
  Try-GitHub-Actions:
    runs-on: [self-hosted, linux]
    steps:
      - name: practice of YAML
        run: |
          echo 'BRANCH NAME is ${{ inputs.branch_name }}'
          time=$(date -d "9 hours""+%H%M%S")
          t_daytime=${day}_${time}
          echo $date
# EOF